services:
  db:
    image: timescale/timescaledb:latest-pg16
    container_name: gtfs-tsdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gtfs_olap
    ports:
      - "5432:5432"
    volumes:
      - tsdb-data:/var/lib/postgresql/data

volumes:
  tsdb-data:
